//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrmMain
{
    using System;
    using System.Collections.Generic;
    
    public partial class tclass_sort_table
    {
        public int class_sort_id { get; set; }
        public int class_sort_1 { get; set; }
        public string class_sort_2 { get; set; }
        public string class_name { get; set; }
        public string class_sort_photo { get; set; }
        public bool class_sort_status { get; set; }
    }
}
